on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: test:latest
  required-check:
    # This job is set as the required status check in the repository settings.
    # If changing this job, make sure to update the required status check under Rulesets.
    name: Required Check
    needs: [test-and-build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check if required jobs succeeded
        run: |
          if [[ "${{ needs.test-and-build.result }}" == "success" ]]; then
            echo "All required jobs succeeded"
            exit 0
          else
            echo "One or more required jobs failed"
            exit 1
          fi
